### ISSUE TITLE
Enable Lidar and Camera in TurtleBot_Description file

### ISSUE THREAD

**Issue by TeamB2024-AuE8230** [TeamB2024-AuE8230/turtlebot_autonav#9]
roscd turtlebot3_description

Ensure the URDF and Model files are updated

**Comment by DevAnandGupta** [comment]
@pkorrapati Please put the updated files here on Git. This would help to know which files to edit, and what lines to add.

**Comment by pkorrapati** [comment]
Link: https://github.com/TeamB2024-AuE8230/Essentials

$ roscd turtlebot3_description

$ gedit turtlebot3_burger.gazebo.xacro

$ gedit turtlebot3_burger.urdf.xacro
